### ISSUE TITLE
The consumer cannot handle a report

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/compliance-backend#12]
It throws "No such file or directory" and then stops to handle next uploads. Tested on openshift.
The log excerpt:
```
E, [2018-11-06T13:15:28.723035 #13] ERROR -- : Exception raised when processing platform.upload.compliance/0 at offset 0 -- Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/storage/52df9f748eabcfea
/opt/app-root/src/app/services/safe_downloader.rb:24:in `initialize'
/opt/app-root/src/app/services/safe_downloader.rb:24:in `copy_stream'
/opt/app-root/src/app/services/safe_downloader.rb:24:in `download'
/opt/app-root/src/app/consumers/compliance_reports_consumer.rb:12:in `process'
/opt/app-root/src/bundle/ruby/2.5.0/gems/racecar-0.4.2/lib/racecar/runner.rb:80:in `block (2 levels) in run'
/opt/app-root/src/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/app-root/src/bundle/ruby/2.5.0/gems/racecar-0.4.2/lib/racecar/runner.rb:79:in `block in run'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:228:in `block (4 levels) in each_message'
/opt/app-root/src/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/instrumenter.rb:21:in `instrument'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/instrumenter.rb:35:in `instrument'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:226:in `block (3 levels) in each_message'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:210:in `each'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:210:in `block (2 levels) in each_message'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:209:in `each'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:209:in `block in each_message'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:395:in `block in consumer_loop'
/opt/app-root/src/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/instrumenter.rb:21:in `instrument'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/instrumenter.rb:35:in `instrument'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:394:in `consumer_loop'
/opt/app-root/src/bundle/ruby/2.5.0/gems/ruby-kafka-0.7.3/lib/kafka/consumer.rb:206:in `each_message'
/opt/app-root/src/bundle/ruby/2.5.0/gems/racecar-0.4.2/lib/racecar/runner.rb:71:in `run'
/opt/app-root/src/bundle/ruby/2.5.0/gems/racecar-0.4.2/lib/racecar.rb:48:in `run'
/opt/app-root/src/bundle/ruby/2.5.0/gems/racecar-0.4.2/lib/racecar/cli.rb:63:in `run'
/opt/app-root/src/bundle/ruby/2.5.0/gems/racecar-0.4.2/lib/racecar/cli.rb:10:in `main'
/opt/app-root/src/bundle/ruby/2.5.0/gems/racecar-0.4.2/exe/racecar:9:in `<top (required)>'
/opt/app-root/src/bundle/ruby/2.5.0/bin/racecar:23:in `load'
/opt/app-root/src/bundle/ruby/2.5.0/bin/racecar:23:in `<top (required)>'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/opt/rh/rh-ruby25/root/usr/bin/bundle:23:in `load'
/opt/rh/rh-ruby25/root/usr/bin/bundle:23:in `<main>'
I, [2018-11-06T13:15:28.723195 #13]  INFO -- : Leaving group `compliance-reports-consumer`
D, [2018-11-06T13:15:28.723315 #13] DEBUG -- : Sending leave_group API request 10 to kafka-1.compliance-qa.svc:29092
D, [2018-11-06T13:15:28.723480 #13] DEBUG -- : Waiting for response 10 from kafka-1.compliance-qa.svc:29092
D, [2018-11-06T13:15:28.728189 #13] DEBUG -- : Received response 10 from kafka-1.compliance-qa.svc:29092
E, [2018-11-06T13:15:28.728339 #13] ERROR -- : Error processing partition platform.upload.compliance/0 at offset 0--

**Comment by quarckster** [comment]
I believe it fixed in #15
